### ISSUE TITLE
Problem with installed script on windows

### ISSUE THREAD

**Issue by Hexagon** [cross-org/env#10]
example script, test.ts:
```ts
import { getAllEnv } from "jsr:@cross/env"
getAllEnv()
```

Runs fine with `deno run -A test.ts`

But... If installing using `deno install -Af test.ts -n testcmd` and executing using `testcmd`, there is an error:

```
error: Uncaught (in promise) TypeError: Key contains invalid characters: "=C:"
                    envVars[key] = Deno.env.get(key);
                                            ^
    at Object.getEnv [as get] (ext:runtime/30_os.js:102:10)
    at getAllEnv (https://jsr.io/@cross/env/1.0.0/mod.ts:202:45)
    at file:///C:/Users/user/source/test/test.ts:3:1
```

This seem to stem from a variable with the key "=C:", added when running a `deno install`ed command

**Comment by Hexagon** [comment]
https://github.com/denoland/deno/issues/23443

**Comment by Hexagon** [comment]
I guess @cross/env could be hotfixed with a try/catch around Deno.env.get
